### ISSUE TITLE
Phone spoofing not working

### ISSUE THREAD

**Issue by jLynx** [pbombnz/SuperKiwi#1]
Hey guys, I'm trying to use the Semble app on my LG G2 (D802) OS:5.0.2, but it says that my phone is not supported, so it doesn't seem to be spoofing my phones information. Can you fix this?

Thanks

**Comment by pbombnz** [comment]
Hi. Sorry for a late response.

Could you enable the debug mode in the UI, then turn on the spoof device feature then try open Semble. Then after the the "Phone not supported message" close the app, open Xposed Installer app, go the logs section, click refresh in the top-right corner, then save the logs (it usually saves it to the internal storage area if you click the option within the Xposed Installer). and then just upload the log file here.

Could you answer these questions as well...
Do other xposed modules work fine?
Do you have SELinux is permissive mode? 
What ROM?
.. I might have more questions later, but for now that will do.

**Comment by jLynx** [comment]
Sorry dude, it seems to be working. It looks like it wasn't working because there was a problem with my xposed install. But its all good now
