### ISSUE TITLE
Not working on rooted phone

### ISSUE THREAD

**Issue by jLynx** [pbombnz/SuperKiwi#2]
I assume there has been a update to Semble because it no longer works on my phone

LG G2 D802 5.0.2

**Comment by jLynx** [comment]
And now its working again after I reinstalled module, disabled it rebooted and enabled then rebooted again. Not sure if this is a bug in the module itself or now

**Comment by pbombnz** [comment]
Okay, I will keep an eye out for this type of behaviour.
