### ISSUE TITLE
Not detecting Semble sim

### ISSUE THREAD

**Issue by jLynx** [pbombnz/SuperKiwi#3]
Hi guys, not sure if this is something you can fix>
But I just upgraded my LG G2 to a OnePlus 3 today and all was going well, I install SuperKiwi but the problem now is that its not detecting my Semble sim card.

The OnePlus 3 is a dual sim phone, so I am guessing that may have something to do with it?
I have tried the sim in both slots with no luck.

Is this something you guys can try fix?

**Comment by pbombnz** [comment]
What's your ROM? Can you confirm that the OP3 has Secure Element NFC? What's the message that comes up when opening the Semble app (word for word)?

**Comment by jLynx** [comment]
@pbombnz I'm on Oxygen OS 3.2.0. The ASB nfc payment "works" so I assume it is secure nfc (not sure how you tell) and this is the exact message: http://i.imgur.com/gruPoDq.png

This is after I have your SuperKiwi enabled btw

## 

With SuperKiwi completely disabled it say "Semble cannot operate on a phone that is rooted...status 1"

With rood detection on the message that comes up is: "Semble is not supported on your phone...status 97"

With the phone spoof and root detection on it says: "You need a semble ready SIM to use semble...status 3 (just like the screenshot above)

**Comment by jLynx** [comment]
@pbombnz Can we try spoofing the phone to a dual sim phone that is supported by Semble such as the Huawei P8 [GRA-L09]?

**Comment by jLynx** [comment]
A quote I found here http://www.semble.co.nz/blog/entry/semble-compatible-phones-part-3

> "Another common question we are asked is why we don’t whitelist dual SIM phones (phones that let you use multiple SIM cards in them). For the same reason that we encourage customers not to keep physical plastic cards on the back of their phones, we don’t want the terminal to get confused and if there are two SIM cards, the terminal gets confused. . Due to our reliance on your phone successfully communicating with you SIM card for these payments, it is unlikely we will be able to support these devices in the near future."

But they do support a few dual sim phones...
